### ISSUE TITLE
Issues while running the example

### ISSUE THREAD

**Issue by ggthedev** [mamaral/MAPageViewController#1]
Hi,
I was trying your control and have found following issues in different simulator settings:
setting: iOS 8.2
Issue: "2015-04-30 19:20:04.820 JVMenuPopover[62622:2018211] <UIVisualEffectView 0x7fe3ba50ec90> is being asked to animate its opacity. This will cause the effect to appear broken until opacity returns to 1.
"

setting: iOS 7.1
Issue: application crashes moment i tap the menu button with following message
"
dyld: lazy symbol binding failed: Symbol not found: _UIAccessibilityIsReduceTransparencyEnabled
  Referenced from: /Users/gauravgupta/Library/Developer/CoreSimulator/Devices/6688E8A4-A011-47FB-8093-D7DF9A6CC39F/data/Applications/808FDF95-4C4D-415B-959B-910FF0AC55F8/JVMenuPopover.app/JVMenuPopover
  Expected in: /Library/Developer/CoreSimulator/Profiles/Runtimes/iOS 7.1.simruntime/Contents/Resources/RuntimeRoot/System/Library/Frameworks/UIKit.framework/UIKit

dyld: Symbol not found: _UIAccessibilityIsReduceTransparencyEnabled
  Referenced from: /Users/gauravgupta/Library/Developer/CoreSimulator/Devices/6688E8A4-A011-47FB-8093-D7DF9A6CC39F/data/Applications/808FDF95-4C4D-415B-959B-910FF0AC55F8/JVMenuPopover.app/JVMenuPopover
  Expected in: /Library/Developer/CoreSimulator/Profiles/Runtimes/iOS 7.1.simruntime/Contents/Resources/RuntimeRoot/System/Library/Frameworks/UIKit.framework/UIKit
"

can u let me know if there is any solution or your control was meant only for iOS 8+?

**Comment by mamaral** [comment]
The issue related to `JVMenuPopover`... I assume you meant to open this issue on [this?](https://github.com/JV17/JVMenuPopover)

**Comment by ggthedev** [comment]
Ya thats very much!!thanks for the direction i will open it on the relevant side.

**Comment by ggthedev** [comment]
Thanks for the info
